### ISSUE TITLE
Trace user feedback with FastAPI

### ISSUE THREAD

**Issue by bukosabino** [Scale3-Labs/langtrace-python-sdk#229]
Hello everyone,

Congratulations on your work, I am in love with Langtrace!

However, I have a problem when I follow the documentation on [traceuserfeedback](https://docs.langtrace.ai/features/traceuserfeedback)

Is it ready to work with FastAPI? Could the `main` function be an endpoint? If it is an endpoint, `spanId` and `traceId` are input parameters that the client has to fill in, and I think this is not the purpose...

Note: I am working with FastAPI, using `@with_langtrace_root_span` and `inject_additional_attributes`.

**Comment by bukosabino** [comment]
Hey, I take a look at the package code and I discover that [with_langrace_root_span](https://github.com/Scale3-Labs/langtrace-python-sdk/blob/782d52a547a0166d0a9e175ebb234c8a77cce328/src/langtrace_python_sdk/utils/with_root_span.py#L39) expects `span_id` and `trace_id` and not `spanId` and `traceId`. So the example works like a churm if you update this.

Please update the documentation.

Thank you very much!

**Comment by alizenhom** [comment]
Hey @bukosabino, 
Apologies for the confusion and really nice catch!
will definitely update the docs thanks for pointing out.

**Comment by bukosabino** [comment]
I have created a pull request: https://github.com/Scale3-Labs/langtrace-docs/pull/45

**Comment by karthikscale3** [comment]
Thanks @bukosabino for correcting it.
