### ISSUE TITLE
Add litellm to options

### ISSUE THREAD

**Issue by krrishdholakia** [Scale3-Labs/langtrace-python-sdk#380]
LiteLLM isn't on your framework options, but it's a supported flow 

<img width="927" alt="Screenshot 2024-10-12 at 4 06 37 PM" src="https://github.com/user-attachments/assets/4ed7a673-2d91-4659-b65e-15841f52a1e1">

**Comment by karthikscale3** [comment]
Thanks @krrishdholakia . Good catch! That list is mostly for analytics. But, we have fixed it

![image](https://github.com/user-attachments/assets/1d009ce0-94cf-4ee4-ac1b-08b5a92be7ae)

See below for a project that uses LiteLLM successfully instrumented using Langtrace

![image](https://github.com/user-attachments/assets/243dd3c1-bde6-49da-8a7d-a0f5d95f6c66)
